server:
  servlet:
    context-path: /api

spring:
  application:
    name: SpringMail
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
              - https://www.googleapis.com/auth/gmail.readonly
  data:
    redis:
      host: localhost
      port: 6379